### ISSUE TITLE
[Feature 1]Produce myCrashVariant Requirements pdf document v0.2 (at SPEC level)

### ISSUE THREAD

**Issue by ImHantu** [CherkashinSergey/INPLS-SED-2017-g08#31]

**Comment by acapozucca** [comment]
Please, split up this issue in three (one for each group member) such that it is clear what is the feature each one is dealing with, and also what is the work related to that feature from the Requirements Analysis viewpoint (e.g. specify use-case instances, specify environment model, etc).

Do the same for the other issues related to the Design Document.

**Comment by CherkashinSergey** [comment]
Not comitted yet. Coordination with team is needed.

**Comment by ImHantu** [comment]
?
